VolgaIT/Controllers/AppsActionsController.cs
using Microsoft.AspNetCore.Mvc;
using VolgaIT.Models;
using VolgaIT.Models.ViewModels;
using VolgaIT.Services.Interface;

namespace VolgaIT.Controllers
{
    public class AppsActionsController : Controller
    {
        private IAppService _appService;
        private IEventService _eventService;

        public AppsActionsController(IAppService appService, IEventService eventService)
        {
            _appService = appService;
            _eventService = eventService;
        }

        [HttpGet]
        public async Task<IActionResult> Settings(string appId)
        {
            App app = await _appService.GetAppByIdAsync(appId);
            var model = new UpdateAppViewModel()
            {
                AppId = app.Id,
                AppName = app.Name,
                AddDateCreate = app.DateCreate.ToString()
            };
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> StatisticsApp(string appId)
        {
            App app = await _appService.GetAppByIdAsync(appId);
            StatisticsAppViewModel model = new StatisticsAppViewModel
            {
                App = app,
                Events = await _eventService.GetAllEventAsync(),
                RequestUsers = app.RequestsUsers.ToList()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteApp(string appId)
        {
            await _appService.RemoveAppByIdAsync(appId);
            return RedirectToAction("ListApp", "UserActions");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateApp(UpdateAppViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _appService.UpdateAppAsync(model);
                    ViewBag.resultUpdateApp = "Успешно сохранено";
                }
                catch
                {
                    ModelState.AddModelError("", "Ошибка сохранения");
                }
            }
            return View("Settings", model);
        }


        [HttpGet]
        public async Task<IActionResult> TimeFilterRequestApp(string timeFilter, string appId)
        {
            App app = await _appService.GetAppByIdAsync(appId);
            StatisticsAppViewModel model = new StatisticsAppViewModel
            {
                App = app,
                Events = await _eventService.GetAllEventAsync(),
                RequestUsers = app.RequestsUsers.ToList()
            };
            return PartialView("PartialTableStat", _appService.TimeFilterRequestApp(timeFilter, model));
        }
    }
}

VolgaIT/Controllers/UserActionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VolgaIT.Models;
using VolgaIT.Models.ViewModels;
using VolgaIT.Services.Interface;

namespace VolgaIT.Controllers
{
    [Authorize(Roles = "user")]
    public class UserActionsController : Controller
    {
        private readonly IUserService _userService;
        private readonly IAppService _appService;
        private readonly IAccountService _accountService;
        private readonly IUserAppsService _userAppsService;

        public UserActionsController(IUserService userService, IUserAppsService userAppsService, IAppService appService, IAccountService accountService)
        {
            _userService = userService;
            _userAppsService = userAppsService;
            _appService = appService;
            _accountService = accountService;
         }

        [HttpGet]
        public async Task<IActionResult> MainPageUser()
        {
            var user = await _userService.GetUserAsync();
            if(user==null)
            {
                await _accountService.LogoutAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(user.UsersApps.Count());
        }

        [HttpGet]
        public async Task<IActionResult> ListApp()
        {
            var user = await _userService.GetUserAsync();
            var userApps = await _appService.GetAppRangeAsync(user.UsersApps.Select(x=>x.AppsId).ToList());
            return View(userApps);
        }

        #region [AddApp]
        [HttpGet]
        public IActionResult AddUserApp(string result)
        {
            var model = new AddAppViewModel { AppId = Guid.NewGuid().ToString() };
            ViewBag.result = result;
            return View(model);
        }

        [HttpPost]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true, Duration = 0)]
        public async Task<IActionResult> AddUserApp(AddAppViewModel model)
        {
            string result = "";
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userService.GetUserAsync();
                    await _appService.AddAppAsync(model);
                    await _userAppsService.AddUserAppAsync(model.AppId, user.Id);
                    result = "Приложение добавлено";
                    return RedirectToAction("AddUserApp", new { result = result});
                }
                catch
                {
                    var allApps = await _appService.GetAllAppsAsync();
                    if (allApps.Select(x => x.Name).Contains(model.AppName))
                    {
                        ModelState.AddModelError("", "Приложение с таким названием уже существует");
                        return View();
                    }
                    else if (allApps.Select(x => x.Id).Contains(model.AppId))
                    {
                        ModelState.AddModelError("", "Приложение с таким Id уже существует");
                        return View();
                    }
                    else if (model.AppName == model.AppId)
                    {
                        ModelState.AddModelError("", "Название приложения должно отличаться от его Id");
                        return View();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Ошибка создания");
                        return View();
                    }
                }
            }
            return View();
        }

        #endregion

        #region [UserProfile]
        [HttpGet]
        public async Task<IActionResult> UserProfile(UpdateProfileViewModel model)
        {
            User user = await _userService.GetUserAsync();
            model.IdUser = user.Id;
            model.NewEmail = user.Email;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditProfile(UpdateProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _userService.EditProfileAsync(model);
                if (result)
                {
                    return RedirectToAction("MainPageUser");
                }
                ModelState.AddModelError("", "Ошибка сохранения");
            }
            ModelState.AddModelError("", "Ошибка сохранения");
            return View("UserProfile");
        }
        #endregion

    }
}

VolgaIT/Views/UserActions/AddUserApp.cshtml
@model VolgaIT.Models.ViewModels.AddAppViewModel
@{
    Layout = "_LayoutUser";
    ViewData["Title"] = "Новое приложение";
}

<section class="add-app-container">
    <h1 class="display-1">Добавление приложения</h1>
    <form method="post" asp-controller="UserActions" asp-action="AddUserApp" class="add-app-form">
        <div class="input-add-app-container">
            <input type="text" placeholder="Id приложения" asp-for="AppId" class="input-add-app">
            <span asp-validation-for="AppId" class="add-app-valid"></span>
        </div>
        <div class="input-add-app-container">
            <input type="text" placeholder="Название приложения" asp-for="AppName" class="input-add-app"/>
            <span asp-validation-for="AppName" class="add-app-valid"></span>
            <div asp-validation-summary="ModelOnly" class="add-app-valid"></div>
        </div>
        <input type="submit" value="Создать" class="input-btn-add-app"/>
        <span class="result-add-app">@ViewBag.Result</span>
    </form>
</section>

VolgaIT/Views/UserActions/ListApp.cshtml
@model List<App>
@{
    Layout = "_LayoutUser";
    //ViewData["Title"] = "Мои приложения";
    ViewData["Title"] = "Мои приложения";
    int counter = 1;
}

<section class="list-app-container">
    <h1 class="display-1">Мои приложения</h1>
    <div class="table-app-container">
        <table>
            <tr class="table-row-app">
                <th>Номер</th>
                <th>Id</th>
                <th>Название</th>
                <th>Дата создания</th>
                <th></th>
            </tr>
        </table>	
        <div class="table-app-data">
            <table>
                @for (int i = 0; i < Model.Count(); i++)
                {
					
                    <tr class="table-row-app">
                        @{
                            counter = i+1;
                        }
                        <td>@counter</td>
                        <td>@Model[i].Id</td>
                        <td>@Model[i].Name</td>
                        <td>@Model[i].DateCreate</td>
                        <td>
                            <a asp-action="StatisticsApp" asp-controller="AppsActions" asp-route-appId="@Model[i].Id">Статистика</a>
                            <a asp-action="Settings" asp-controller="AppsActions" asp-route-appId="@Model[i].Id">Настройки</a>
                        </td>
                    </tr>	
                }
            </table>
        </div>	
    </div>
</section>

VolgaIT/Views/UserActions/MainPageUser.cshtml
@model int
@{
    Layout = "_LayoutUser";
    ViewData["Title"] = "Главная";
}

<section class="main-page-user">
    <h1>количество<br>моих<br>приложений:</h1>
    <p>@Model</p>
</section>

VolgaIT/Views/UserActions/UserProfile.cshtml
@using VolgaIT.Models.ViewModels
@model UpdateProfileViewModel
@{
    Layout = "_LayoutUser";
}

<section class="profile">
    <h1 class="display-1">Профиль</h1>
    <form method="post" asp-controller="UserActions">
        <div class="container-one-input">
            <input type="hidden" asp-for="IdUser"/>
            <div>
                <p class="lead">Почта: </p>
                <input type="text" placeholder="email" asp-for="NewEmail" class="input-profile"/>
            </div>
            <div asp-validation-summary="@ValidationSummary.ModelOnly" class="valid-save-email"></div>
        </div>
        <div class="container-btn-profile">
            <input type="submit" value="Сохранить" asp-action="EditProfile" class="btn-save-profile"/>
        </div>
    </form>    
</section>